### PR TITLE
Make front page visible

### PR DESCRIPTION
**Pull request by fureigh**
This commit includes:
* an anonymous (i.e., logged-out) user role
* an authenticated user role
* an administrator role (not to be confused with UID 1)
* standard settings regarding registration, etc.

These are basic user settings and roles, without which the front page isn't visible to anyone but the superuser.

To apply these changes, run bin/drush config:import or docker-compose up.

Addresses an issue spotted in https://github.com/18F/osc-website-pa/pull/86.

### CODE REVIEW

**Review by timothy-spencer — COMMENTED** [review]
This doesn't seem to work for me, but maybe I'm unsure of how this is supposed to work?

I start this up with ```docker-compose down -v ; docker rmi osc-website-pa_web ; bin/composer install ; docker-compose up```, then go to http://localhost:8080/, I get a "Page not found", where I was expecting to get redirected to node/1 or something like that.  Is there something I'm missing?

**Comment by timothy-spencer** [comment]
Oh huh.  I did a `bin/drush config:import`, and it imported stuff, and now it works.  How is it that this doesn't get imported automatically when we do the full `docker-compose down -v ; docker rmi osc-website-pa_web ; bin/composer install ; docker-compose up`?

**Comment by fureigh** [comment]
@timothy-spencer Can you confirm that the commands for importing 1) config and 2) default content are both getting run as part of the new build process?

For context from the approach we'd been using previously, see the `# Sync configs from code` and `# Import initial content` lines of `bootstrap.sh`.

**Comment by timothy-spencer** [comment]
Yes, I haven't changed any of that:

https://github.com/18F/osc-website-pa/blob/master/bootstrap.sh#L59-L69

I imported and exported the config and checked that in, and things now seem to work.  I'm going to test a bit more and then probably approve this.

**Review by timothy-spencer — APPROVED** [review]
Tested this, works from scratch.  Yay!

**Comment by mogul** [comment]
I'm looking at porting this back to `cf-ex-drupal8`... Where do the `default_config_hash` values come from?

**Comment by fureigh** [comment]
@mogul Test the import, of course, but it shouldn't be a problem. The `default_config_hash` values come from the Default Content module ([here's an overview](https://www.drupal.org/docs/8/modules/default-content-for-d8/overview)).

A _site UUID_ mismatch would cause config import to choke, but that's why running `bootstrap.sh` resets the UUID.

I'll ping you in a minute to 🍐.

**Comment by fureigh** [comment]
^ and `bootstrap.sh` gets called on every build. 👍

**Comment by fureigh** [comment]
@mogul But also, I don't think you need to port it over! It should be working fine on `cf-ex-drupal8` already. I filed https://github.com/18F/cf-ex-drupal8/commit/7cd88a6a74aa4922abfc6f2a34ceb84a6a94fb02 after checking this.

**Pull request merged**
