### PR TITLE
Set up USWDS custom theme

### LINKED ISSUE #47: Resolve USWDS loading issues
The USWDS files aren't loading correctly locally. This may be due to them 404-ing, not being included in the base templates, or we need some changes in the base templates. We're not sure which is the issue yet.

### This task is done when...
 - [ ] USWDS assets load correctly and are reflected on the page.

### PR DESCRIPTION
**Pull request by line47**
- Removed duplicate files from the root that were in the `app` dir where all things Drupal live.
- Moved the USWDS theme from `app/web/themes` to `app/web/themes/custom`
- Added `assets` dir under the `uswds` custom theme to get styling working 

I also made **U.S. Web Design Standards 8.x-1.0-beta3** the default theme in the Drupal admin

screen shot 2019-01-04 at 12 13 22 pm
 

This fixes #47

### CODE REVIEW

**Comment by fureigh** [comment]
Good catch on the duplicate files! More TK.

**Comment by tbaxter-18f** [comment]
I think we should gitignore the fonts and stuff in assets.

**Comment by fureigh** [comment]
@line47 I'm working on confirming this with a fresh build.

In the meantime: the word `custom` has a technical meaning in Drupal. Themes, modules and libraries someone else maintains are `contributed`; themes, modules and libraries solely supported by this site are `custom`. Using this terminology, then, `uswds` is a `contrib`[uted] theme, not a `custom` one.

That means the `uswds` theme should live inside a directory called `contrib` instead of one called `custom`, sure. But it also raises a more important point about architecture and workflow:

It's a Drupal best practice to store overrides and customizations separately, rather than modifying contributed modules/themes or Drupal core directly. This approach helps to improve maintainability and, relatedly, security. In keeping with that, the `uswds` theme is built to allow creation of subthemes (hence the `osc` theme in https://github.com/18F/osc-website-pa/pull/63). So the/a subtheme — a theme that inherits from another theme — is where site-specific code changes should be made.

**Comment by fureigh** [comment]
Heading to a doctor's appointment but I'll file a PR against this branch afterward, incorporating the above. (Where's the "one team one dream" emoji when I need it?)

**Comment by line47** [comment]
@tbaxter-18f Ready for a review 👀

**Pull request merged**
